// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: cmd/gRPCGeo/geo.proto

package gRPCGeo

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAddressGeocode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
}

func (x *RequestAddressGeocode) Reset() {
	*x = RequestAddressGeocode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddressGeocode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddressGeocode) ProtoMessage() {}

func (x *RequestAddressGeocode) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddressGeocode.ProtoReflect.Descriptor instead.
func (*RequestAddressGeocode) Descriptor() ([]byte, []int) {
	return file_cmd_gRPCGeo_geo_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAddressGeocode) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RequestAddressGeocode) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type ResponseAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ResponseAddress) Reset() {
	*x = ResponseAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddress) ProtoMessage() {}

func (x *ResponseAddress) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddress.ProtoReflect.Descriptor instead.
func (*ResponseAddress) Descriptor() ([]byte, []int) {
	return file_cmd_gRPCGeo_geo_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAddress) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Road        string `protobuf:"bytes,1,opt,name=Road,proto3" json:"Road,omitempty"`
	Town        string `protobuf:"bytes,2,opt,name=Town,proto3" json:"Town,omitempty"`
	County      string `protobuf:"bytes,3,opt,name=County,proto3" json:"County,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Postcode    string `protobuf:"bytes,5,opt,name=Postcode,proto3" json:"Postcode,omitempty"`
	Country     string `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	CountryCode string `protobuf:"bytes,7,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_cmd_gRPCGeo_geo_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetRoad() string {
	if x != nil {
		return x.Road
	}
	return ""
}

func (x *Address) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *Address) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type ResponseAddressGeocode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat string `protobuf:"bytes,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon string `protobuf:"bytes,2,opt,name=Lon,proto3" json:"Lon,omitempty"`
}

func (x *ResponseAddressGeocode) Reset() {
	*x = ResponseAddressGeocode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddressGeocode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddressGeocode) ProtoMessage() {}

func (x *ResponseAddressGeocode) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_gRPCGeo_geo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddressGeocode.ProtoReflect.Descriptor instead.
func (*ResponseAddressGeocode) Descriptor() ([]byte, []int) {
	return file_cmd_gRPCGeo_geo_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseAddressGeocode) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *ResponseAddressGeocode) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

var File_cmd_gRPCGeo_geo_proto protoreflect.FileDescriptor

var file_cmd_gRPCGeo_geo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2f, 0x67, 0x65,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f,
	0x22, 0x3b, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x6e, 0x67, 0x22, 0x3d, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x2a, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xb7, 0x01, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x6f, 0x77, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4c, 0x6f, 0x6e, 0x32, 0x9e, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47, 0x65, 0x6f, 0x63,
	0x6f, 0x64, 0x65, 0x1a, 0x18, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x0d, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x10, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x1a, 0x1f, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47, 0x65, 0x6f, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_gRPCGeo_geo_proto_rawDescOnce sync.Once
	file_cmd_gRPCGeo_geo_proto_rawDescData = file_cmd_gRPCGeo_geo_proto_rawDesc
)

func file_cmd_gRPCGeo_geo_proto_rawDescGZIP() []byte {
	file_cmd_gRPCGeo_geo_proto_rawDescOnce.Do(func() {
		file_cmd_gRPCGeo_geo_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_gRPCGeo_geo_proto_rawDescData)
	})
	return file_cmd_gRPCGeo_geo_proto_rawDescData
}

var file_cmd_gRPCGeo_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_gRPCGeo_geo_proto_goTypes = []any{
	(*RequestAddressGeocode)(nil),  // 0: gRPCGeo.RequestAddressGeocode
	(*ResponseAddress)(nil),        // 1: gRPCGeo.ResponseAddress
	(*Address)(nil),                // 2: gRPCGeo.Address
	(*ResponseAddressGeocode)(nil), // 3: gRPCGeo.ResponseAddressGeocode
}
var file_cmd_gRPCGeo_geo_proto_depIdxs = []int32{
	2, // 0: gRPCGeo.ResponseAddress.Address:type_name -> gRPCGeo.Address
	0, // 1: gRPCGeo.GeoService.SearchAnswer:input_type -> gRPCGeo.RequestAddressGeocode
	2, // 2: gRPCGeo.GeoService.GeocodeAnswer:input_type -> gRPCGeo.Address
	1, // 3: gRPCGeo.GeoService.SearchAnswer:output_type -> gRPCGeo.ResponseAddress
	3, // 4: gRPCGeo.GeoService.GeocodeAnswer:output_type -> gRPCGeo.ResponseAddressGeocode
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_gRPCGeo_geo_proto_init() }
func file_cmd_gRPCGeo_geo_proto_init() {
	if File_cmd_gRPCGeo_geo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_gRPCGeo_geo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestAddressGeocode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_gRPCGeo_geo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_gRPCGeo_geo_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_gRPCGeo_geo_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseAddressGeocode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_gRPCGeo_geo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_gRPCGeo_geo_proto_goTypes,
		DependencyIndexes: file_cmd_gRPCGeo_geo_proto_depIdxs,
		MessageInfos:      file_cmd_gRPCGeo_geo_proto_msgTypes,
	}.Build()
	File_cmd_gRPCGeo_geo_proto = out.File
	file_cmd_gRPCGeo_geo_proto_rawDesc = nil
	file_cmd_gRPCGeo_geo_proto_goTypes = nil
	file_cmd_gRPCGeo_geo_proto_depIdxs = nil
}
